# Generated by Django 4.0.4 on 2022-06-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='product_type',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
