# Generated by Django 4.0.4 on 2022-06-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productdetails_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='stock',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
