# Generated by Django 4.0.4 on 2022-06-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productdetails_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='barcode',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
